-- USERS

CREATE TABLE users (
                       id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name     VARCHAR(255) NOT NULL,
                       email    VARCHAR(255) NOT NULL,
                       password VARCHAR(255) NOT NULL,
                       role     VARCHAR(20)  NOT NULL DEFAULT 'USER',
                       is_verified BOOLEAN NOT NULL DEFAULT false,
                       two_factor_email BOOLEAN NOT NULL DEFAULT FALSE,
                       verification_code VARCHAR(100),
                       verification_code_expiration TIMESTAMP,
                       created_at TIMESTAMP NOT NULL DEFAULT now(),
                       phone_number   VARCHAR(15) NOT NULL,
                       date_of_birth  DATE NOT NULL
);
-- unikát na email
ALTER TABLE users ADD CONSTRAINT users_email_key UNIQUE (email);

-- ADDRESSES
CREATE TABLE addresses (
                           id      BIGSERIAL    PRIMARY KEY,                   -- AUTO_INCREMENT → BIGSERIAL
                           street  VARCHAR(255) NOT NULL,
                           city    VARCHAR(255) NOT NULL,
                           region VARCHAR(255) NOT NULL,
                           country   VARCHAR(255) NOT NULL,
                           zip     VARCHAR(255) NOT NULL,
                           user_id BIGINT       NOT NULL
                               REFERENCES users (id) ON DELETE NO ACTION,
                           CONSTRAINT addresses_users_id_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE NO ACTION
);

/*ALTER TABLE addresses
    ADD CONSTRAINT addresses_users_id_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE NO ACTION;*/
-- (stejně jako v MySQL ponechávám index na cizí klíč)
CREATE INDEX addresses_users_id_fk ON addresses (user_id);



