-- USERS

CREATE TABLE users (
                       id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name     VARCHAR(255) NOT NULL,
                       email    VARCHAR(255) NOT NULL,
                       password VARCHAR(255) NOT NULL,
                       role     VARCHAR(20)  NOT NULL DEFAULT 'USER',
                       is_verified BOOLEAN NOT NULL DEFAULT false,
                       two_factor_email BOOLEAN NOT NULL DEFAULT FALSE,
                       verification_code VARCHAR(100),
                       verification_code_expiration TIMESTAMP,
                       created_at TIMESTAMP NOT NULL DEFAULT now(),
                       phone_number   VARCHAR(15) NOT NULL,
                       date_of_birth  DATE NOT NULL,
                       avatar_id BIGINT
);
-- unikát na email
ALTER TABLE users ADD CONSTRAINT users_email_key UNIQUE (email);


CREATE TABLE images (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        image_url TEXT NOT NULL,
                        public_id TEXT NOT NULL,
                        ord INT NOT NULL,
                        type VARCHAR(50) NOT NULL,
                        created_at TIMESTAMP NOT NULL DEFAULT now(),
                        user_id BIGINT NOT NULL,
                        CONSTRAINT fk_images_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Volitelné indexy pro rychlost
/*CREATE INDEX idx_images_idea_id ON images(idea_id);*/
CREATE INDEX idx_images_user_id ON images(user_id);


ALTER TABLE users
    ADD CONSTRAINT fk_users_profile_image
        FOREIGN KEY (avatar_id) REFERENCES images(id) ON DELETE SET NULL;



