CREATE TABLE ideas
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(255) NOT NULL,
    description TEXT         NOT NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT now(),
    user_id BIGINT       NOT NULL,
    CONSTRAINT fk_ideas_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

/*ALTER TABLE ideas
    ADD CONSTRAINT fk_ideas_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;*/

-- rychlé dotazy podle uživatele
CREATE INDEX idx_ideas_user_id ON ideas(user_id);

/*CREATE TABLE idea_images (
                             id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             idea_id   BIGINT NOT NULL,
                             image_url TEXT   NOT NULL,
                             ord       INT    NOT NULL,
                             created_at TIMESTAMP NOT NULL DEFAULT now(),
                             CONSTRAINT fk_idea_images_idea
                                 FOREIGN KEY (idea_id) REFERENCES ideas(id) ON DELETE CASCADE
);

-- Unikátní pořadí v rámci jedné ideje
CREATE UNIQUE INDEX ux_idea_images_idea_ord ON idea_images(idea_id, ord);*/
CREATE TABLE images (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        image_url TEXT NOT NULL,
                        public_id TEXT NOT NULL,
                        ord INT NOT NULL,
                        type VARCHAR(50) NOT NULL,
                        created_at TIMESTAMP NOT NULL DEFAULT now(),
                        /*idea_id BIGINT NOT NULL,*/
                        user_id BIGINT NOT NULL,

                        /*CONSTRAINT fk_images_idea FOREIGN KEY (idea_id) REFERENCES ideas(id) ON DELETE CASCADE,*/
                        CONSTRAINT fk_images_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Volitelné indexy pro rychlost
/*CREATE INDEX idx_images_idea_id ON images(idea_id);*/
CREATE INDEX idx_images_user_id ON images(user_id);


ALTER TABLE users
    ADD CONSTRAINT fk_users_profile_image
        FOREIGN KEY (avatar_id) REFERENCES images(id) ON DELETE SET NULL;

















CREATE TABLE goals
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title   VARCHAR(255),
    is_done BOOLEAN DEFAULT false,
    idea_id BIGINT,
    CONSTRAINT FK_GOALS_ON_IDEA FOREIGN KEY (idea_id) REFERENCES ideas (id)
);

CREATE TABLE sections
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(255) NOT NULL,
    description TEXT         NOT NULL,
    idea_id     BIGINT       NOT NULL,
    CONSTRAINT FK_SECTIONS_ON_IDEA FOREIGN KEY (idea_id) REFERENCES ideas (id)
);



