CREATE TABLE artists (
                         id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name     VARCHAR(255) NOT NULL,
                         email    VARCHAR(255) NOT NULL,
                         password VARCHAR(255) NOT NULL,
                         role     VARCHAR(20)  NOT NULL DEFAULT 'ARTIST',
                         is_verified BOOLEAN NOT NULL DEFAULT false,
                         two_factor_email BOOLEAN NOT NULL DEFAULT FALSE,
                         verification_code VARCHAR(100),
                         verification_code_expiration TIMESTAMP,
                         created_at TIMESTAMP NOT NULL DEFAULT now(),
                         phone_number   VARCHAR(15) NOT NULL,
                         date_of_birth  DATE NOT NULL,
                         avatar_id BIGINT,
                         plays BIGINT NOT NULL DEFAULT 0,
                         song_number BIGINT NOT NULL DEFAULT 0
);
ALTER TABLE artists ADD CONSTRAINT artists_email_key UNIQUE (email);

CREATE TABLE songs (
                        id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        title VARCHAR(255) NOT NULL,
                        duration_seconds INT NOT NULL,
                        release_date DATE NOT NULL,
                        genre VARCHAR(100),
                        plays BIGINT NOT NULL DEFAULT 0,
                        artist_id BIGINT NOT NULL,
                        CONSTRAINT fk_songs_artist FOREIGN KEY (artist_id) REFERENCES artists(id) ON DELETE CASCADE,
                        type VARCHAR(20) NOT NULL DEFAULT 'SINGLE'
);


CREATE TABLE images (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        image_url TEXT NOT NULL,
                        public_id TEXT NOT NULL,
                        ord INT NOT NULL,
                        type VARCHAR(50) NOT NULL,
                        created_at TIMESTAMP NOT NULL DEFAULT now(),
                        song_id BIGINT NOT NULL,
                        CONSTRAINT fk_images_song FOREIGN KEY (song_id) REFERENCES songs(id) ON DELETE CASCADE
);

CREATE INDEX idx_images_song_id ON images(song_id);

ALTER TABLE artists
    ADD CONSTRAINT fk_artists_profile_image
        FOREIGN KEY (avatar_id) REFERENCES images(id) ON DELETE SET NULL;




/*
CREATE TABLE goals
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title   VARCHAR(255),
    is_done BOOLEAN DEFAULT false,
    idea_id BIGINT,
    CONSTRAINT FK_GOALS_ON_IDEA FOREIGN KEY (idea_id) REFERENCES ideas (id)
);

CREATE TABLE sections
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(255) NOT NULL,
    description TEXT         NOT NULL,
    idea_id     BIGINT       NOT NULL,
    CONSTRAINT FK_SECTIONS_ON_IDEA FOREIGN KEY (idea_id) REFERENCES ideas (id)
);


CREATE TABLE ideas
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(255) NOT NULL,
    description TEXT         NOT NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT now(),
    user_id BIGINT       NOT NULL,
    CONSTRAINT fk_ideas_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
-- rychlé dotazy podle uživatele
CREATE INDEX idx_ideas_user_id ON ideas(user_id);


-- Unikátní pořadí v rámci jedné ideje
CREATE UNIQUE INDEX ux_idea_images_idea_ord ON idea_images(idea_id, ord);*/
